export const marcas=[{"marcas":"Chevrolet"},
{"marcas":"Toyota"},
{"marcas":"Jeep"},
{"marcas":"Chevrolet"},
{"marcas":"Mazda"},
{"marcas":"Chevrolet"},
{"marcas":"Mazda"},
{"marcas":"BMW"},
{"marcas":"Infiniti"},
{"marcas":"Jaguar"},
{"marcas":"Porsche"},
{"marcas":"BMW"},
{"marcas":"Mercedes-Benz"},
{"marcas":"Lincoln"},
{"marcas":"Maserati"}];